
<html>


<body>

<h1> Normal Table Look-up </h1>


<TAble border=2>
<tr>
   <TD> Type of Probability Question           </TD>
</tr>
  

<TR>     <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="A"> <img src="gA.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="B"> <img src="gB.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="C"> <img src="gC.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="D"> <img src="gD.bmp">  </TD>
<TR>     <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="E"> <img src="gE.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="F"> <img src="gF.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="G"> <img src="gG.bmp">  </TD>
         <TD>   <INPUT TYPE=RADIO NAME=GO VALUE="H"> <img src="gH.bmp">  </TD>
     
   
 
 
</table>

</FORM>



</body>
</html>
